# full_config.yaml
tune:
  name: "PendulumTest"
  connection:
    sim_ip: "127.0.0.1"
    real_ip: "192.168.42.1"

motor:
  type: "sts3215"
  id: 11
  error_gain: 0.165
  winding_resistance: 5.5
  torque_constant: 2.5
    limits:
    position:
      min: -90
      max: 90
    velocity: 180
    torque: 100
  gains:
    kp: 32.0
    kd: 0.0
    ki: 0.0

testbed:
  type: "pendulum"
  pendulum:
    mass: 0.5
    length: 0.3
    zero_position: 0.0
  trajectories:
    - name: "identification_sine"
      type: "sine"
      parameters:
        amplitude: 45
        frequency: 0.5
        duration: 10
      safety:
        max_position: 60
        max_velocity: 180
    - name: "identification_chirp"
      type: "chirp"
      parameters:
        amplitude: 30
        frequency: 0.1
        sweep_rate: 0.05
        duration: 20