sysid:
  # Hardware configuration
  actuator_id: 11
  motor_name: "sts3215v12"
  ip: "192.168.42.1"
  
  # Pendulum parameters
  # Mass is in kg
  # Length is in meters
  mass: 0.453592
  length: 0.150846
  
  # Motor parameters
  error_gain: 1.0
  winding_resistance: 2.1
  torque_constant: 0.0955
  
  # Test configuration
  repetitions: 3
  kp_values: [4, 8, 16, 32]
  trajectories: 
    - "lift_and_drop"
    - "sin_sin"
    - "up_and_down"

 